import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/layouts/Header";

const notoJp = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${notoJp.variable} antialiased bg-orange-100`}>
        <div className="flex justify-center items-center fixed z-[1000] mt-[15px] w-full">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
